sudo: false
language: python
python:
- '3.6'
script:
- echo "skipping tests for now .."
deploy:
  provider: pypi
  user: l-althueser
  password:
    secure: awMXHVNP9ojBiKHB/fRvsw0gmEQbgFlqVjIpCsJffdVvI9BfxEenysC50l4xkOfxela1327WGfIav27hfDz32p8BYX0DSS68x9mBQsqMVHB3NEk9jCz2Qgg9tlu/qsVr7QxuBuPGDqvm+kg5dWDgdFjuK4rR4namJI0qvEwkVyGSKmS3uPjVOk7gEkZGv/2cSqFj9hd1Bj4BPK+YykeucA85T7/EZrTPcC4PlPSlLpVfu1BXFAIPD5V9g2p9+QwFWOlCyOFh0NMa8k3RHXZxm3XUBeQno3vuuMsB9e+oT8vHS0eV6uCtbf3KGAdQEpoJTi2Sk5mB0jdRxp7Dsc30uSBE48whWaUoJ6jwdRGeb4rnby68CcQOgzW7vESq//KRyUA6vOITn3CAPnpEUc/NVCeDbOaRXNzybf67NzL7L2XLxtOrw1xNMd9T6IF9rcqBae/G2ZXzEZyY9pCcJNmw3O7sR87C3DYuUpTvOy9TfWW6LuTvEAiEH7g4+Faa9oaqpcVYmB9TSoufdiDl00JdL56gGOS2iura46+C8l2qszVPiAUorUlfE7/z9A2MPV4N8/nwcZ06SG7b428OWweBbnql7HrTgbXjFtqy37+tRcWvu6p8InMKtVKLHGW/+C6t9lOhxVI8eu9wvdRFBe/N9/wxlYu8VaynwVI0hf+4Y2U=
  on:
    tags: true
    repo: l-althueser/nbindex-jupyter
