sudo: false
language: python
python:
- '3.6'
script:
- echo "skipping tests for now .."
deploy:
  provider: pypi
  user: l-althueser
  password:
    secure: LV9DiEMenVu2jnkA/ci/6ct7QpQzjf4wvWbLmRNZIc2DgIxKjkXQZk8+/yjHW5LzJL0MwAmWQq5CZqmJmZ+fTqYjSEHNDlf8MkgRI7ipy3rIbH4PMRpXJRUz96sk6FFlqxa9G2xRoygCzT5qum43pK2haRv1xXFpWtv+6D+gJ9BCASpgDY1P/9CKP10lyS30RJvzv4sTRPsD9d0aAfcrpMo0tc4Yvk6P5AraxCiPUuKwr+GS3yH0bPLvXcNv2jf7uE1FmTKq5P8qopPvkl7MkViCYMF8QYWHnu1TELq63H6ll8G7k+AZa/xSo/1gFwYki/Sug5ABOnrA9zqHWZx8Q6AdT7cxNXLMSsgYYqOOlBgx41rAagY0tyrw91w6oeENvG8IggDOW9YL0kS3G3vHXBmaqJoER0HzuyyC+hLWnw8N1K/i626XJX+4IbOTezj4HnJjuQpVcPn06bxgmJiIj1He09b3bcR+Q6m1KtrBSWhfF9hRapNeR3x3JrnigabIvX3bvvzF8r/ZB/IeNvZE0abY6qLkPY+r6Dgr7jHyR9n31dr8bx2L7wR7lMtIPUOPL+Tes5sdU3G4Zl/XRQVZ07/+ZlIFnm1zV1LSmucVXffiExTfEEo4IjiACKuAUczN9dZi3lSjRou8/5ZgxVk4rlAubKqRE9oagN3G2gFDkiY=
  on:
    tags: true
    repo: l-althueser/nbindex-jupyter
