sudo: false
language: python
python:
- '3.6'

script:
- echo "skipping tests for now .."

deploy:
  provider: pypi
  user: l-althueser
  password: "Pe684UKpBBsFJc0R4Q6S/13oXC9GnFF2k5YzdJmIooK1gPhcHGsLUtVvl1N3x8rabFmUy/26IMiXWRtihlRxzcyZX7kugE9yHXaAftRov4tdE5ps7IMSqdJFo0qA+dS6qNswPqsBpmSuFZt1zhTmQmMYxMsvpg7IEgAflKsrlCeykSVT9prSRoWcxZ52APtKlVkcMdyxzlUpqVE4yKUc0SSgkOPPaHYkd90vC0SDHg4C6ujhrz9YqeFFMUPczREQrUBcYG7RZ25MWSjRsrpNIuxHXWFyJ8OHu5esj3e9JAAQKLUwBY286F1y17XLojY3caCHtfoCKq4pGSRi9EAmtEXp5YhUC6dc1XgHNpp7cwuNaXoMOb1qrUt/mTkttPWdzeAQIwLoAwuNJHCs4fyRXwuuw/G6jRkz+BsqoiZrtBGvuKp4FbmPP+Z14Zix1BeMlG876GPw9Vb33oORAtmhAo5bPXZWPKm6RrI6A3wInDIS+JlEXYJmR8Rnh5qyHRX5e/gwGXudXqrX0Z+syXjTAA1gz4SR+yk3PUYxcQQejYJNJlVsWYW/tnEyTgV0VT3h4iqYK1WPFuiV+J91EUa/MI00A+pNajXdxZOE7bPG1bhr94oZ79Hmh1Aa+J3J2S/gxzOlRoBfa2iTAso+S15+plUC0LsHk1eV32V4vDdx2Yw="
  on:
    tags: true
    repo: l-althueser/nbindex-jupyter
