dist: trusty
language: python
sudo: false
deploy:
  provider: pypi
  user: l-althueser
  password:
    secure: iTqRr+byZtY9OsPli5ta+e86Me98EsviUjwPz9dTVQyp6EyysCQ0Atoo3Mt/1peenJoMMoJJkbmC1Ml+RHzHq6ilstVzAYVQnFikQW5jYJ52OdUXRk1NNnGevTXE+9yUkh+C013u7xtZQCAwrpzwIrrTjHy4OUxUUtHwOMkzCTxGS2/Uyw0qpt1QyF9+yc3kuk5e394qGDoCn9PIhffnOh7DVIzQOyShvpXNSxcIECGJLSn7FA80w5Ox4FbAgAPas8NSIFvaKPUVvXj24FObypjLxVpevv4ntLQVTsHMam846lTbFTpXaavT8Fh/5/MpAhdbM/mxh7Qov3ofc6+c3TjP0bRcA3KxVmpqgLHM/n28PwSGtGZcCNh20wpPoRbgdrFyfSMbkui5qzI2TdWIJlFo6gTadxPp4bct226BrYJxNDmBhL7cl6/m+mgd1muuQ0tezCawVepRLlZaoQL/AhBlNkKLjleU+JrzGkQowWpo7ySJVHPBmVV0thtWphDDYCjGNWa3/Bx9IUBy1tf/RF+WBMYcVFF41WiKAD+ypFXaiXHFFvEg1i6mwkab60Ltrrh9Rav+JOej3VHy1c9U/UHN+KgH9VrXL/x9yhTr99IK8C/A297avYtsulazv0zLEU251y4M8uwwXa5jJoKVLj9JF1KKiu1DqbQCIuh+FY0=
  on:
    tags: true
