sudo: false
language: python
python:
- '3.6'

script:
- echo "skipping tests for now .."

deploy:
  provider: pypi
  user: l-althueser
  password:
    secure: Sq9f4cJSd4FxeOgDT6lPrvUBpeR+KiKFhDfb0uSVr+Ym9/0lBXerj8bIqHVuS/tLPkiXrPW0Jpm/mR3Id95mRE3Wdeiq2M217y0dO9d9vA/RSJap1TTgoYBd0Fst3R0MbH57efmK1YoXb47ytHHrxevq/hKAzbuwUHDfHwEWgh0SebeVZ9OLDsaSgnTJrIOkZBP6imzp5U6X/yLX3IknLkThns65v0ze6HXfMrSnONDADZhJl/ISQazEht+gZ39Jddkw44qhp6VSMxJsHLiP2uCZ2/etAUuvPLE55gkufGyi/Y6wCKdFltP34UBXKTquTN/wYDUtgWY330GpSp9zXUp6YN5l9XjAC8G0ANqp1WatGW8dEqqJbIbP+i3ocKqOzQpPmglAP7yNOOzxsv5ta5BFD5CUAa6aqm/f0beyH8PixJpt0ODlWmEv4jXNEafhPMMmf7zV4fDwzGTCZy4qkULUAzrVvZLYkDqz8q/YiDIj4Kbwv1/462JMtWReiW51/XT7NByheIFQ94V3Y33gTOudv7EicVIP2zooZHurKT8Yrzkaw7AyGzL+5SUrxqU6cuXj2fI9/4xniJsL//hyvGX2ROPZ9AR5ugBILtu+jik0wDSjQjd1geQgbxfnJOklx/XexP9P2jkbLHZMCs9uqhUCSVzVa4Mi0AQlqq9BXwU=
  on:
    tags: true
    repo: l-althueser/nbindex-jupyter
